### PR TITLE
add: gen 9 mini sprites

### PR DESCRIPTION
**Pull request by Fexxix**
added gen 9 mini sprites and fixed some bugs like nidoran male and female sprites not showing up and also for flabebe's

## Screenshots

image
image
image

i recently added the gen 9 mini sprites color scripts to the og phoney badger repo too:
https://gitlab.com/Fexxix/pokemon-colorscripts

i have created a PR for it too but he has been inactive for a long time

### CODE REVIEW

**Comment by ckaznable** [comment]
Thanks for you awesome PR!!!

I want to make sure that these sprites sources are allowed to be open source? If it's okay, I'll merge PR right away.

**Comment by Fexxix** [comment]
> Thanks for you awesome PR!!!
> 
> I want to make sure that these sprites sources are allowed to be open source? If it's okay, I'll merge PR right away.

i got the sprites from this resource pack right here: https://www.pokecommunity.com/threads/generation-9-resource-pack-v21-1.527398/

its meant to be a free thing for rom hack developers so i guess its okay?

**Comment by ckaznable** [comment]
> > Thanks for you awesome PR!!!
> > I want to make sure that these sprites sources are allowed to be open source? If it's okay, I'll merge PR right away.
> 
> i got the sprites from this resource pack right here: https://www.pokecommunity.com/threads/generation-9-resource-pack-v21-1.527398/
> 
> its meant to be a free thing for rom hack developers so i guess its okay?

It looks fine. Can you help me add gen 9 sprites source link to the README?

**Comment by Fexxix** [comment]
> > > Thanks for you awesome PR!!!
> > > I want to make sure that these sprites sources are allowed to be open source? If it's okay, I'll merge PR right away.
> > 
> > 
> > i got the sprites from this resource pack right here: https://www.pokecommunity.com/threads/generation-9-resource-pack-v21-1.527398/
> > its meant to be a free thing for rom hack developers so i guess its okay?
> 
> It looks fine. Can you help me add gen 9 sprites source link to the README?

sure but these are fan made and aren't really available via any link unlike other poke sprites.

they were originally like this

image

and then i cut them in half like so

image

currently, these are only available on my machine so should I upload them somewhere so they can be sourced?

**Comment by ckaznable** [comment]
> > > > Thanks for you awesome PR!!!
> > > > I want to make sure that these sprites sources are allowed to be open source? If it's okay, I'll merge PR right away.
> > > 
> > > 
> > > i got the sprites from this resource pack right here: https://www.pokecommunity.com/threads/generation-9-resource-pack-v21-1.527398/
> > > its meant to be a free thing for rom hack developers so i guess its okay?
> > 
> > 
> > It looks fine. Can you help me add gen 9 sprites source link to the README?
> 
> sure but these are fan made and aren't really available via any link unlike other poke sprites.
> 
> they were originally like this
> 
> image
> 
> and then i cut them in half like so
> 
> image
> 
> currently, these are only available on my machine so should I upload them somewhere so they can be sourced?

I see. I don't think it needs to be uploaded to somewhere.

I'll just merge PR. Thank you for your contribution!

**Review by ckaznable — APPROVED** [review]
LGTM

**Comment by Fexxix** [comment]
> LGTM

Hello again, I noticed this today so I thought I would let you know too. Please give them credit in the README. The [roadmap](https://github.com/ckaznable/poketex?tab=readme-ov-file#roadmap) would be a good place to do it I think.

image

**Comment by ckaznable** [comment]
> Hello again, I noticed this today so I thought I would let you know too. Please give them credit in the README. The [roadmap](https://github.com/ckaznable/poketex?tab=readme-ov-file#roadmap) would be a good place to do it I think.

I've added the creator to the Readme. Thank you again.

**Pull request merged**
